#pragma once

#define SYSCALL_TEST 1
#define SYS_YIELD 2
#define SYS_EXIT 3
#define SYS_FORK 4
#define SYS_GETPID 5
#define SYS_SIGNAL 6
#define SYS_KILL 7
#define SYS_SIGPROCMASK 8
#define SYS_SIGRETURN 9
#define SYS_PASS_VERIFY 10
#define SYS_PASS_STORE 11
#define SYS_PASS_EXISTS 12
#define SYS_WRITE 13
#define SYS_GETCHAR 14
#define SYS_PUTCHAR 15
#define SYS_GETUID 16
#define SYS_SETUID 17
#define SYS_GET_USERNAME 18
#define SYS_CLEAR_SCREEN 19
#define SYS_SHELL_EXIT 20
#define SYS_PASS_GET_UID 21